motion:
  side: right
  sensitivity: 1.0
  smoothing: 0.25
  min-distance: 8

left:
  analog-stick:
    wheel:
      scroll_direction: vertical
      scroll_speed: 0.8

  buttons:
    down: _
    up: _
    right: _
    left: _
    sr: _
    sl: _
    l: _
    zl: _
    minus: _
    l-stick: _
    capture: _

right:
  analog-stick:
    mouse:
      mouse_speed: 2.0

  buttons:
    y: _
    x: _
    b: _
    a: _
    right_sr: _
    right_sl: _
    r: _
    zr: _
    plus: _
    r-stick_btn: _
    home: _
