motion:
  side: right
  sensitivity: 1.0

left:
  analog-stick:
    wheel:
      scroll_direction: vertical
      scroll_speed: 0.8

  buttons:
    down: down
    up: up
    right: right
    left: left
    left_sr: ctrl+c
    left_sl: ctrl+v
    l: shift
    zl: ctrl
    minus: esc
    l-stick_btn: ctrl+a
    capture: windows

right:
  analog-stick:
    mouse:
      mouse_speed: 2.0

  buttons:
    y: w
    x: a
    b: s
    a: d
    right_sr: ctrl+z
    right_sl: ctrl+y
    r: mouse-right
    zr: mouse-left
    plus: enter
    r-stick_btn: backspace
    home: toggle-motion
